template: Hello, %s!
defaultName: Stranger

logging:
  level: info
  appenders:
    - type: file
      currentLogFilename: logs/info.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: logs/info-%d.log
      archivedFileCount: 5
      timeZone: UTC

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 9008

    #this requires the alpn-boot library on the JVM's boot classpath
    #- type: h2
    #  port: 8445
    #  keyStorePath: example.keystore
    #  keyStorePassword: example
  adminConnectors:
    - type: http
      port: 9009

swagger:
  resourcePackage: com.test.domain.resource
  schemes:
    - http

hystrixConfig:
  hystrix.command.GithubConnector#getUserProfile(String).execution.isolation.thread.timeoutInMilliseconds: 7000
  hystrix.command.BingConnector#getBingImgs(int,int).execution.isolation.thread.timeoutInMilliseconds: 7000


githubApiConfig:
  baseUrl: "https://api.github.com"
  getUserProfile:
    connectTimeoutMillis: 2000
    readTimeoutMillis: 5000

bingApiConfig:
  baseUrl: "https://cn.bing.com/"
  getBingImgs:
    connectTimeoutMillis: 2000
    readTimeoutMillis: 5000

